name: Build/Publish Docker Images and, optionally, Singularity Images on CVMFS


on:
  workflow_dispatch:
    inputs:
      image:
        description: |
          The full-qualified image (tagless) --
            include a registry if not storing with dockerhub
          EXAMPLE: 'ghcr.io/foo/bar', 'foo/bar', etc.
        required: true
      mode:
        description: |
          The mode to use:
            BUILD                   - build and publish 'inputs.image'
            CVMFS_BUILD             - BUILD, then request CVMFS to build and persist 'inputs.image'
            CVMFS_REMOVE            - request CVMFS to delete 'inputs.cvmfs_remove_images'
            CVMFS_REMOVE_THEN_BUILD - CVMFS_REMOVE, then CVMFS_BUILD
        required: true
      registry_username:
        description: |
          IF USING PUBLISHING TO A CONTAINER REGISTRY (else, var is ignored):
            The username needed for publishing the image to a container registry -- 
            if your registry does not need a username, use `registry_token`. 
          EXAMPLE: use $ {{ secrets.DOCKERHUB_USERNAME }} (no space after $)
        required: false
      registry_token:
        description: |
          IF USING PUBLISHING TO A CONTAINER REGISTRY (else, var is ignored):
            The token/password needed for publishing the image to a container registry.
          EXAMPLE: use $ {{ secrets.DOCKERHUB_TOKEN }} (no space after $)
          EXAMPLE: use $ {{ secrets.GITHUB_TOKEN }} (no space after $)
        required: false
      gh_cvmfs_token:
        description: |
          IF USING CVMFS (else, var is ignored):
            A PAT so the workflow can git push to GitHub (used for CVMFS build/removal requests)
        required: false
      cvmfs_dest_dir:
        description: |
          IF USING CVMFS (else, var is ignored):
            The CVMFS directory to place the singularity image built from the docker image
        required: false
      cvmfs_remove_tags:
        description: |
          IF REMOVING ON CVMFS (else, var is ignored):
            The image **TAGS** (i.e. 'bar' in 'baz/foo:bar') to remove on CVMFS -- newline-delimited
            tags can be a pattern-based or verbatim -- see https://github.com/WIPACrepo/build-singularity-cvmfs-action
          EXAMPLE: '$ {{ github.ref_name }}-[SHA]' (no space after $)
        required: false
      free_disk_space:
        description: |
          IF BUILDING VERY LARGE IMAGES (else, var is ignored):
            Whether to free disk space on the GitHub runner before building the image
        required: false
        default: "false"
      build_platform:
        description: |
          IF BUILDING IMAGE (else, var is ignored):
            The CPU architecture platform to use when building the image
          EXAMPLE: '$ {{ github.event.inputs.platform || env.DEFAULT_PLATFORM }}' (no space after $)
        required: false
        default: "linux/amd64"


jobs:

  image-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          ref: ${{ github.sha }}

      - name: Determine mode steps
        run: |
          set -euo pipefail; echo "now: $(date -u +"%Y-%m-%dT%H:%M:%S.%3N")"
          
          echo "DO_1_CVMFS_REMOVE=false" >> "$GITHUB_ENV"
          echo "DO_2_BUILD=false" >> "$GITHUB_ENV"
          echo "DO_3_CVMFS_BUILD=false" >> "$GITHUB_ENV"

          case "${{ inputs.mode }}" in
            CVMFS_REMOVE|CVMFS_REMOVE_THEN_BUILD)
              echo "DO_1_CVMFS_REMOVE=true" >> "$GITHUB_ENV"
              ;;
          esac

          case "${{ inputs.mode }}" in
            BUILD|CVMFS_BUILD|CVMFS_REMOVE_THEN_BUILD)
              echo "DO_2_BUILD=true" >> "$GITHUB_ENV"
              ;;
          esac

          case "${{ inputs.mode }}" in
            CVMFS_BUILD|CVMFS_REMOVE_THEN_BUILD)
              echo "DO_3_CVMFS_BUILD=true" >> "$GITHUB_ENV"
              ;;
          esac

      - name: Validate image format
        run: |
          set -euo pipefail; echo "now: $(date -u +"%Y-%m-%dT%H:%M:%S.%3N")"
          
          if [[ ! "${{ inputs.image }}" =~ ^[^/]+/[^/]+(/[^/]+)?$ ]]; then
            echo "::error::'image' must be in form 'namespace/image' or 'registry/namespace/image'"
            exit 1
          fi
          last_segment=$(basename "${{ inputs.image }}")
          if [[ "$last_segment" == *:* || "$last_segment" == *@* ]]; then
            echo "::error::'image' must not include a tag or digest"
            exit 1
          else
            echo "IMAGE_NAME=$last_segment" >> "$GITHUB_ENV"
          fi

      - name: Remove CVMFS images (if applicable)
        if: env.DO_1_CVMFS_REMOVE == 'true'
        run: |
          set -euo pipefail; echo "now: $(date -u +"%Y-%m-%dT%H:%M:%S.%3N")"
          
          if [[ -z "${{ inputs.cvmfs_remove_tags }}" ]]; then
            echo "::error::cvmfs_remove_tags must be given"
            exit 1
          fi
          python -c '
          import os
          image_name = os.environ["IMAGE_NAME"]
          tags = """${{ inputs.cvmfs_remove_tags }}"""
          print("\n".join(f"{image_name}:{t.strip()}" for t in tags.splitlines() if t.strip()))
          ' > delete_image_nametags.txt
          echo "delete_image_nametags<<EOF" >> "$GITHUB_OUTPUT"
          cat delete_image_nametags.txt >> "$GITHUB_OUTPUT"
          echo "EOF" >> "$GITHUB_OUTPUT"

      - name: Run CVMFS removal action
        if: env.DO_1_CVMFS_REMOVE == 'true'
        uses: WIPACrepo/build-singularity-cvmfs-action@v2.0
        with:
          github_token: ${{ inputs.gh_cvmfs_token }}
          dest_dir: ${{ inputs.cvmfs_dest_dir }}
          delete_image_nametags: ${{ steps.remove.outputs.delete_image_nametags }}

      - name: Free disk space
        if: env.DO_2_BUILD == 'true' && inputs.free_disk_space == 'true'
        uses: jlumbroso/free-disk-space@main
        with:
          docker-images: false

      - name: Docker metadata
        if: env.DO_2_BUILD == 'true'
        id: docker_meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ inputs.image }}
          tags: |
            type=sha,prefix={{branch}}-,enable=${{ github.ref_type == 'branch' }}
            type=semver,pattern={{major}},enable=${{ github.ref_type == 'tag' }}
            type=semver,pattern={{major}}.{{minor}},enable=${{ github.ref_type == 'tag' }}
            type=semver,pattern={{major}}.{{minor}}.{{patch}},enable=${{ github.ref_type == 'tag' }}

      - name: Container registry log-in (Docker Hub)
        if: env.DO_2_BUILD == 'true' && ! startsWith(inputs.image, 'ghcr.io/')
        uses: docker/login-action@v2
        with:
          username: ${{ inputs.registry_username }}
          password: ${{ inputs.registry_token }}

      - name: Container registry log-in (GHCR)
        if: env.DO_2_BUILD == 'true' && startsWith(inputs.image, 'ghcr.io/')
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ inputs.registry_token }}

      - name: Setup QEMU
        if: env.DO_2_BUILD == 'true' && contains(inputs.build_platform, 'arm')
        uses: docker/setup-qemu-action@v2

      - name: Setup Buildx
        if: env.DO_2_BUILD == 'true'
        uses: docker/setup-buildx-action@v2

      - name: Docker build and push
        if: env.DO_2_BUILD == 'true'
        uses: docker/build-push-action@v3
        with:
          context: .
          platforms: ${{ inputs.build_platform }}
          push: true
          tags: ${{ steps.docker_meta.outputs.tags }}
          labels: ${{ steps.docker_meta.outputs.labels }}

      - name: Build Singularity on CVMFS
        if: env.DO_3_CVMFS_BUILD == 'true'
        uses: WIPACrepo/build-singularity-cvmfs-action@v2.0
        with:
          github_token: ${{ inputs.gh_cvmfs_token }}
          dest_dir: ${{ inputs.cvmfs_dest_dir }}
          build_images: ${{ steps.docker_meta.outputs.tags }}
