name: ci/cd

on:
  push:
    # only on branch pushes
    branches: [ '**' ]
    tags-ignore: [ '**' ]

jobs:

  ############################################################################
  # TAG + RELEASE
  #############################################################################

  tag-and-release:
    # only run on main/default
    if: format('refs/heads/{0}', github.event.repository.default_branch) == github.ref
    uses: WIPACrepo/wipac-dev-workflows/.github/workflows/tag-and-release.yml@main  # main -> dogfooding
    permissions: # for GITHUB_TOKEN
      contents: write
    with:
      project-type: gha-workflow
      version-style: 'X.Y'
      more-ignore-paths: |
        !.github/workflows/**
