name: lint-python.yml

on:
  workflow_call:
    inputs:
      default-branch:
        description: |
          Your repo's default branch (e.g., main)
          HINT: Use '$ {{ github.event.repository.default_branch }}' (no space after $)
        required: true
        type: string
      py-matrix-json:
        description: |
          The JSON string of the matrix of Python versions to lint against
          HINT: Use '$ {{ needs.py-versions.outputs.matrix }}' (no space after $)
        required: true
        type: string
      max-complexity:
        description: |
          The max allowed McCabe complexity value per function
          <10:   easier to understand
          10-15: medium complexity (ideal range)
          >15:   harder to understand and maintain
        required: false
        default: 15
        type: number
      max-statements:
        description: |
          The max number of statements per function
        required: false
        default: 50
        type: number

jobs:

  mypy:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        py3: ${{ fromJSON(inputs.py-matrix-json) }}
    steps:
      - uses: actions/checkout@v6
        with:
          ref: ${{ github.sha }}  # lock to triggered commit (github.ref is dynamic)
          fetch-depth: 0  # setuptools-scm needs to access git tags
      - uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.py3 }}
      - uses: WIPACrepo/wipac-dev-mypy-action@v2.0

  ruff-whole-repo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
          ref: ${{ github.sha }}  # lock to triggered commit (github.ref is dynamic)
      - uses: astral-sh/ruff-action@v3
        with:
          args: "--version"  # noop, just install ruff
      - name: Ruff base (repo-wide; respect repo config)
        env:
          MAX_COMPLEXITY: ${{ inputs.max-complexity }}
          MAX_STATEMENTS: ${{ inputs.max-statements }}
        run: |
          set -euo pipefail; echo "now: $(date -u +"%Y-%m-%dT%H:%M:%S.%3N")"
          # note: ruff will use the project's minimum Python version from pyproject.toml
          ruff check \
              --output-format github \
              --extend-select C901,PLR0915 \
              --config "lint.mccabe.max-complexity=${MAX_COMPLEXITY}" \
              --config "lint.pylint.max-statements=${MAX_STATEMENTS}" \
              .

  ruff-branch-changes:
    # Only run on non-default branches
    if: ${{ github.ref_type == 'branch' && (github.head_ref || github.ref_name) != inputs.default-branch }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
          ref: ${{ github.sha }}  # lock to triggered commit (github.ref is dynamic)
      - name: Determine reusable workflow ref
        id: here
        run: |
          set -euo pipefail; echo "now: $(date -u +"%Y-%m-%dT%H:%M:%S.%3N")"
          ref="$(yq -r '.. | .uses? | select(. != null)
              | select(test("WIPACrepo/wipac-dev-workflows/\\.github/workflows/lint-python\\.yml@"))
              | sub("^.*@"; "")' $GITHUB_WORKFLOW_REF | head -n 1)"
          echo "here_ref=${ref}" >> "$GITHUB_OUTPUT"
      - uses: actions/checkout@v6
        with:
          repository: WIPACrepo/wipac-dev-workflows  # aka, here
          ref: ${{ steps.here.outputs.here_ref }}
          path: .wipac-dev-workflows
      - uses: astral-sh/ruff-action@v3
        with:
          args: "--version"  # noop, just install ruff
      - name: Ruff PR-touched lines (stricter than repo-wide)
        env:
          DEFAULT_BRANCH: ${{ inputs.default-branch }}
          RUFF_SELECT: "I,UP,FA"
        run: |
          set -euo pipefail; echo "now: $(date -u +"%Y-%m-%dT%H:%M:%S.%3N")"
          # note: ruff will use the project's minimum Python version from pyproject.toml
          .wipac-dev-workflows/tools/ruff-this.sh
